apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-log-triage

resources:
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/postgres-statefulset.yaml
  - k8s/postgres-service.yaml

secretGenerator:
  - name: ai-log-triage-secret
    envs:
      - .env
